---
driver:
  name: vagrant
  customize:
    memory: 10000
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
  network:
  - ["forwarded_port", {guest: 3306, host: 9191}]
  - ["forwarded_port", {guest: 8080, host: 8080}]
  - ["forwarded_port", {guest: 8088, host: 8088}]
  - ["forwarded_port", {guest: 8181, host: 8181}]
  - ["forwarded_port", {guest: 9088, host: 9088}]
  - ["forwarded_port", {guest: 4848, host: 4444}]
  - ["forwarded_port", {guest: 50070, host: 51070}]
  - ["forwarded_port", {guest: 50075, host: 51075}]
  - ["forwarded_port", {guest: 9200, host: 9200}]

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.4.3

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[ndb::install]
      - recipe[hops::install]
      - recipe[elastic::install]
      - recipe[ndb::mgmd]
      - recipe[ndb::ndbd]
      - recipe[ndb::mysqld]
      - recipe[hops::ndb]
      - recipe[hops::nn]
      - recipe[hops::dn]
      - recipe[elastic::default]
      - recipe[hopsfindbench::default]
      - recipe[hopsfindbench]

    attributes:
         java:
           jdk_version: 7
         authorization:
            sudo:
              users: ['vagrant']
              passwordless: true
              include_sudoers_d: true
         kagent:
            private_ips: ["10.0.2.15"]
            enabled: true
         elastic:
            default:
                private_ips: ["10.0.2.15"]
                public_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         ndb:
            mgmd:
               private_ips: ["10.0.2.15"]
            ndbd:
               private_ips: ["10.0.2.15"]
            mysqld:
               private_ips: ["10.0.2.15"]
            memcached:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            enabled: "true"
         hops:
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
            use_hopsworks: "false"
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "true"

